### ISSUE TITLE
Demo doesn't work in Firefox Quantum

### ISSUE THREAD

**Issue by ImreC** [akulubala/vue-product-zoomer#1]
Cool product! Unfortunately your demo doesn't work on Firefox Quantum@latest. Didn't dig deeper into the cause.

**Comment by akulubala** [comment]
@ImreC thanks for the feedback, I'm using ubuntu 16.04, Firefox version 58.01.All well to me. Can you show more details?

**Comment by ImreC** [comment]
All is well now. Maybe the server serving the images had a glitch. Cool product! Will probably use this in my next project.
