### ISSUE TITLE
Font Awesome render as <i> not <svg>

### ISSUE THREAD

**Issue by luhegi** [akulubala/vue-product-zoomer#13]
can you help me with this issue? it working correctly but the icon not rendering as svg but as
```<i aria-hidden="true" class="fa fa-angle-right"></i>```
</code>
</pre>

**Comment by akulubala** [comment]
it should be SVG, which version and browser you are using?

**Comment by luhegi** [comment]
i'm using "version": "2.0.11"

**Comment by akulubala** [comment]
version 2.0.11 using fontawsome 4, it should be an SVG file,  maybe you should check if your package installed correctly, can't help you without more details.

**Comment by akulubala** [comment]
@luhegi, I was wrong with the version, it's using fontawesome 5, can't help you if you can't provide more details.

**Comment by luhegi** [comment]
i'm using https://github.com/cretueusebiu/laravel-vue-spa, he using font awesome 5 in resources/assets/js/plugins/fontawesome.js

**Comment by akulubala** [comment]
@luhegi I've been checked again with larave-vue-spa, there was no issue for using this plugin, please make sure you are using it correctly. This issue should be closed now since it's not this plugins problem.

**Comment by luhegi** [comment]
ok, thanks for checking. i'll try to fix it
