### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by drosendo** [akulubala/vue-product-zoomer#14]
Hi,

Great component you added, im loving it so far. Have 2 questions.

1.  Is there a option to disable the thumbnails just have the main image, remove the "control-box" (using CSS to hide it at the moment)
2. Is there a way to dynamically update the image with new image?
3. Is there a destroy? if so how can I call it?

Im not using "gallery" but on single image, and I when user click some other image, I want to update the image in the product zoomer.

Hope I explained myself.

Cheers,
David

**Comment by akulubala** [comment]
Hi @drosendo, Glad you like this package. Unfortunately, for now, this package can't fit your requirement, there have no option to remove "control-box" and can't update image from other sources than from control box. If you can show me what exactly effects you want to fulfill?

**Comment by drosendo** [comment]
I have managed.

1. Is there a option to disable the thumbnails just have the main image, remove the "control-box" 
Hide via CSS

2. Is there a way to dynamically update the image with new image?
using the vue :key the image gets updated when key changes

3.Is there a destroy? if so how can I call it?
No need thanks to the above.

But I did found issues where the pane & container get positioned very far from the image. The 'inline-zoomer' works as expected.
Didn't have time to debug it.

Cheers,
Davd

**Comment by Rim-777** [comment]
@drosendo Could you please explain  to me about point 2?
where you change :key to  update with new image?
Usually the key is used in iteration such as v-for, but there is  no vi-for in 
<ProductZoomer
  :base-images="images"
  :base-zoomer-options="zoomerOptions"
/>
Looking forward to your replay
Timo
