### ISSUE TITLE
document is not defined 

### ISSUE THREAD

**Issue by hailt1911** [akulubala/vue-product-zoomer#15]
Hi,

When i try to import it i got an error document is not defined
Screenshot: 
![image](https://user-images.githubusercontent.com/22976644/46282149-f15f7300-c59a-11e8-8009-abae9c209905.png)
Anyone can help me?

Thanks and Best Regards,
Harry

**Comment by janmyszkier** [comment]
Can you please provide 
- the node version 
-  vue-sf version 
so we can reproduce?

**Comment by hailt1911** [comment]
> Can you please provide
> 
> * the node version
> * vue-sf version
>   so we can reproduce?

Hi I'm using node v9.11.1 and use branch master of https://github.com/DivanteLtd/vue-storefront

Thank you

**Comment by janmyszkier** [comment]
please use node version pointed out in dockerfile
https://github.com/DivanteLtd/vue-storefront/blob/master/docker/vue-storefront/Dockerfile
so 8.X and try again

**Comment by shubham0503** [comment]
Hello @janmyszkier I am using 10.14 still I am getting an error "document is not defined".

Thank you
