### ISSUE TITLE
Dynamic Product Zoomer

### ISSUE THREAD

**Issue by icangku** [akulubala/vue-product-zoomer#2]
I have if conditional, if user click variant of a product, product zoomer will use variantImages1 data, but it doesnt work well

`<ProductZoomer v-show="variant" :baseImages="variantImages" :baseZoomerOptions="zoomerOptions"></ProductZoomer>`
`<ProductZoomer v-show="!variant" :baseImages="images" :baseZoomerOptions="zoomerOptions2"></ProductZoomer>`

`<ProductZoomer v-if="variant" :baseImages="variantImages" :baseZoomerOptions="zoomerOptions"></ProductZoomer>`
`<ProductZoomer v-else" :baseImages="images" :baseZoomerOptions="zoomerOptions2"></ProductZoomer>`

`variantImages : { 'thumbs' : [], 'normal_size' : []}`

` for (let index = 0; index < images.length; index++) {`
                       ` this.variantImages.thumbs = [{'id' : index+1, 'url' : images[index]}]`
                       ` this.variantImages.normal_size = [{ 'id' : index+1, 'url' : images[index]}]`
                  `  }`
i'm using vuejs2

![a](https://user-images.githubusercontent.com/14269158/39979766-9627624a-5772-11e8-86e1-78be3dd04585.png)

and the images doesnt show

**Comment by akulubala** [comment]
Hi @icangku , please show me your full code of this part? Can't locate the issue with your current infomations

**Comment by icangku** [comment]
Here's I have default images that loaded statically, but users need to choose one of some variants, an example user chooses color red, then Vue will load images data of that variant, how do I replace the showing images with the variant's images

`<ProductZoomer v-show="!variant" :baseImages="images" :baseZoomerOptions="zoomerOptions2"></ProductZoomer>
<ProductZoomer v-show="variant" :baseImages="variantImages" :baseZoomerOptions="zoomerOptions"></ProductZoomer>`

I have tried like this

`  for (let index = 0; index < images.length; index++) {
                        this.variantImages.thumbs.push({id : index+1, url : images[index]})
                        this.variantImages.normal_size.push({id : index+1, url : images[index]})
                        this.variantImages.large_size.push({id : index+1, url : images[index]})
                    }
                    this.$children[1].choosedThumb = {id : 1, url : images[1]}`

but it doesn't show the zoom box

**Comment by icangku** [comment]
I've tried like this also
<ProductZoomer v-bind:baseImages="{images : !variant, variantImages : variant}" :baseZoomerOptions="zoomerOptions"></ProductZoomer>

but not working

**Comment by akulubala** [comment]
Hi @icangku, this plugin need calculate zoomer box size before it showing, you can't using v-show to control it. I'm not sure if you can achieve your request.Try using CSS `visibility: hidden`, and don't forget `namespace` for each product-zoomer.

**Comment by icangku** [comment]
if(this.variant){
   this.images = this.variantImages
}else{
   this.images = this.defaultImages
}
                    
<ProductZoomer :baseImages="images" :key="Date.now()" :baseZoomerOptions="zoomerOptions"></ProductZoomer>

not it works, but data-zoom not changing, how do i achieve this?
