### ISSUE TITLE
Not zooming

### ISSUE THREAD

**Issue by DarKCoder666** [akulubala/vue-product-zoomer#32]
Everything connected correctly and working without any errors. But, it is not zooming the image. I tried to pass 'thumb', 'normal_size' and 'large_size' - no result.

 

>  
const images = {

        thumbs: [
          {
            id: 1,
            url:
              "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__340.jpg"
          },
          {
            id: 2,
            url:
              "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__340.jpg"
          },
          {
            id: 3,
            url:
              "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__340.jpg"
          }
        ],
        normal_size: [
          {
            id: 1,
            url:
              "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__340.jpg"
          },
          {
            id: 2,
            url:
              "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__340.jpg"
          },
          {
            id: 3,
            url:
              "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__340.jpg"
          }
        ],
        large_size: [
          {
            id: 1,
            url:
              "https://j.plenio.de/images/igallery/resized/401-500/jplenio_DSC02004-430-4000-4000-100.jpg"
          },
          {
            id: 2,
            url:
              "https://j.plenio.de/images/igallery/resized/401-500/jplenio_DSC02004-430-4000-4000-100.jpg"
          },
          {
            id: 3,
            url:
              "https://j.plenio.de/images/igallery/resized/401-500/jplenio_DSC02004-430-4000-4000-100.jpg"
          }
        ]
      };

`      <product-zoomer :base-images="getZoomerImages"></product-zoomer>
`

**Comment by DarKCoder666** [comment]
![Sketch](https://user-images.githubusercontent.com/16527574/58455548-6b042c80-813b-11e9-9e3b-939c9dcff7be.png)

**Comment by akulubala** [comment]
should be some css issues, can you provider more code about when you using this component?

**Comment by akulubala** [comment]
try new version
