### ISSUE TITLE
Zoom postition not accurate

### ISSUE THREAD

**Issue by Siddaramappa** [akulubala/vue-product-zoomer#33]
there is small issue with the position for zoomed image can anyone give the solution
![Screen Shot 2019-06-10 at 1 18 02 PM](https://user-images.githubusercontent.com/41416742/59180507-c514e100-8b82-11e9-8fca-a10638c4d3eb.png)

**Comment by akulubala** [comment]
@Siddaramappa your parent element should be relative

**Comment by Siddaramappa** [comment]
if we don't have any top bar or nav bar in top it working fine... but the issue is if we place the navbar on top this issue is happening.. as you suggest i tried the parent element is relative but we getting same result...

<div class="col-md-4" style="position: relative">
                <product-zoomer :base-images="images" :base-zoomer-options="zoomerOptions" ></product-zoomer>
            </div>

**Comment by akulubala** [comment]
@Siddaramappa are you using bootstrap?

**Comment by Siddaramappa** [comment]
yes i using  Bootstrap 4
For any further queries please leave us message. We’d love to chat.

Thanks & Regards

Siddaramappa N N | Sr. Front End Developer
Appnings Software Solutions Pvt Ltd
#4F, 4th Floor, Rich Homes, Richmond Road, Bangalore - 560025
 L: 080 2222544 | www.appnings.com
<https://www.google.com/url?q=http://www.appnings.com&sa=D&source=hangouts&ust=1535616362761000&usg=AFQjCNFU5z9HiIgE8Kx117oGUdBQGEWe0g>

**Comment by Siddaramappa** [comment]
Yes i using bootstrap 4

**Comment by akulubala** [comment]
@Siddaramappa , there hava some issue with bootstrap grid system, I remeber its child div inherit parent position strategy. you can try to solve it by investigate from there.Or using other css framework like bluma.

**Comment by Siddaramappa** [comment]
okay thanks we try it out thank you so much!!
