### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by bankerrajendra** [akulubala/vue-product-zoomer#34]
[Vue warn]: Failed to mount component: template or render function not defined.

**Comment by akulubala** [comment]
@bankerrajendra normally this happens because webpack for vue is not configured properly.

try this 

`
resolve: { 
    alias: { 
        'vue$': 'vue/dist/vue.js' 
    }, 
    extensions: [‘*’, ‘.js’, ‘.vue’, ‘.json’] 
}, 
`
for you webpack configuration

**Comment by bankerrajendra** [comment]
I am using laravel-mix for laravel vue project.

Added this node_modules\laravel-mix\src\builder\WebpackConfig.js

buildResolving() {
        this.webpackConfig.resolve = {
            extensions: ['*', '.js', '.jsx', '.vue', '.json'],

            alias: {
                vue$: 'vue/dist/vue.common.js'
            }
        };

        return this;
    }

But still issue is there with same error
