### ISSUE TITLE
when ssr it returns an error "document is not defined"

### ISSUE THREAD

**Issue by Asyncinfo** [akulubala/vue-product-zoomer#37]

**Comment by Asyncinfo** [comment]
as the title says, I can't find a way to solve this error.

I find a tip that use require to import this lib，that brings an new error, "did you register your component correctly" 

The codes like below:
if (typeof window !== 'undefined') {
    const ProductZoomer = require('vue-product-zoomer')
    Vue.use(ProductZoomer)
}

this way will not meet the error "document is not defined" but bring the error“ Unknown custom element: <ProductZoomer> - did you register the component correctly? For recursive components, make sure to provide the "name" option”

Can anyone help me?

**Comment by Svenson7** [comment]
I encountered the same issue today. Adding .default after require solved it:

const ProductZoomer = require('vue-product-zoomer').default

**Comment by svenehmer** [comment]
I encountered the same issue today. Adding .default after require solved it:

const ProductZoomer = require('vue-product-zoomer').default

**Comment by Asyncinfo** [comment]
@svenehmer 
It works for me，thank you！
