### ISSUE TITLE
Doesn't work at all with last 3.0.0 version

### ISSUE THREAD

**Issue by dashqa** [akulubala/vue-product-zoomer#39]
Hello! 
Here it is the example - https://codesandbox.io/s/vue-template-pu1wy
As you see, there is no thumb-list visibility and zoom feature doesn't work.
If we change version of dependancy on 2.0.11 it's working.

**Comment by akulubala** [comment]
It's working when not using from code sandbox, not quite sure what's the problem. you can try a demo from your own computer.

**Comment by dashqa** [comment]
I tried it in my project and it doesn't work, thats why I used to try in code sandbox.
Don't know why is that, there is no errors in console. Also I noticed object "drift" is null (vue dev tools) and computed styles aren't generated.
![Screenshot at Jul 29 19-08-08](https://user-images.githubusercontent.com/1376668/62063923-80c5c900-b234-11e9-9d51-c6b48a1acbb7.png)
![Screenshot at Jul 29 19-09-03](https://user-images.githubusercontent.com/1376668/62063926-80c5c900-b234-11e9-9a69-9b523c590d76.png)

**Comment by akulubala** [comment]
@dashqa there have `window.addEventListener("load", () => {})` for drift property. could you check your code for this reason? my demo was working fine.

**Comment by belamov** [comment]
exactly same problem here
haven't figured out what is wrong, seems like event listener on 'load' event isn't triggering, but have no idea why

**Comment by MicroDreamIT** [comment]
for single page application style is not applying at the time to load.

**Comment by Enjoyer1** [comment]
Same problem, working fine in v2.0.11

**Comment by akulubala** [comment]
Hey @Enjoyer1 , need to know more details about how you use this plugin, there have a [demo](https://github.com/akulubala/nuxt-product-zoomer-demo) you can give a try.
