### ISSUE TITLE
Using with Nuxt

### ISSUE THREAD

**Issue by Deifinger** [akulubala/vue-product-zoomer#4]
Hi!
I'm using ProductZoomer component with Nuxt, but getting error.
That's how I include component in another Vue-component:
`
const ProductZoomer =
  typeof window !== "undefined" ? require("vue-product-zoomer") : ""
`

Error:
`[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.`

**Comment by akulubala** [comment]
Hi @Deifinger, this issues is because this package I use the template instead render function, it needs to be compiled before running, I believe you are using runtime build. You can try to solve this by adding below code to your webpack config file.
 `resolve:
 {
   alias: {
      'vue': 'vue/dist/vue.js'
   }
}`

**Comment by Deifinger** [comment]
@akulubala it doesn't work. I added what you mentioned above, but in Nuxt style:

nuxt.config.js
```
module.exports = {
  build: {
    plugins: [
      { src: "~/plugins/product-zoomer.js", ssr: false }
    ],
    vendor: [
      "vue-product-zoomer"
    ],
    extend(config, { isDev, isClient }) {
      config.resolve.alias["vue"] = "vue/dist/vue.js"
    }
  }
}
```

component.vue
```
<template>
  <product-zoomer :base-images="images"></product-zoomer>
</template>

<script>
import ProductZoomer from "vue-product-zoomer"

export default {
  components: {
    ProductZoomer
  },
  data() {
    return {
      images: {
        // images data
      }
    } 
  }
</script>
```

And get NuxtServerError:
> render function or template not defined in component: anonymous

Please, take a look at [error screenshot](http://dl3.joxi.net/drive/2018/06/05/0028/1460/1856948/48/3486420c3a.jpg)

**Comment by akulubala** [comment]
Hi @Deifinger , It seems not this plugins problem, I did some dig for your error. Found this issue from nuxt.js[https://github.com/nuxt/nuxt.js/issues/2792](url), let's wait from nuxt.js

**Comment by hkmsadek** [comment]
Any solution you guys found? I am having same problem :(

**Comment by hkmsadek** [comment]
Hi, I solved it like this... 

In my nuxt config file I used 

`plugins: [
      {src: '~plugins/zoom', ssr: false}
   ],`

and 
`build: {
    vendor:[ 'vue-product-zoomer'] 
  },`

and in my zoom.js 
I have 

`import Vue from 'vue';
import ProductZoomer from 'vue-product-zoomer'
Vue.component('ProductZoomer', ProductZoomer);`

Remimber DON'T IMPORT OR REGISTER THE COMPONENT IN YOUR .VUE FILE BECAUSE ITS ALREADY GLOBALLY REGISTERED.. 
Hope, it helps..

**Comment by Deifinger** [comment]
@hkmsadek yeah, it works, but nevertheless in console i see the error:
```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

**Comment by hkmsadek** [comment]
Yes, as far as I know, it will keep showing on page refresh or reload. It won't show when you visit like spa using nuxt link..

**Comment by hkmsadek** [comment]
let me know if there are solution for this error, but for now we can ignore it

**Comment by besnikh** [comment]
To fix the [Vue warn] you can follow @hkmsadek except I didn't include it to my build just as a plugin and ssr false flag. 

After that in your component you just do a v-if after mounted 

```
<product-zoomer
     :base-images="images"
      :base-zoomer-options="zoomerOptions"
        v-if="showImg"
       >
 </product-zoomer>
```
and in mounted: 

```
mounted () {
    this.showImgl = true
  }

```

But not my problem is that it is showing an font-awesome error 
`vue-carousel.min.js:6 GET http://localhost:3000/assets/fonts/fontawesome-webfont.af7ae50.woff2 net::ERR_ABORTED`

How can I get rid of this error, and after mounted it's destroying all my icons..

**Comment by akulubala** [comment]
Hi @all, for this issue been a while, there have a new version just released, font problem solved by using fontaswsome 4. new install method updated to:  


    import ProductZoomer from 'vue-product-zoomer'
    Vue.use(ProductZoomer);


doc will update soon.
for Nuxt problem just need add it to plugin, check doc here: https://nuxtjs.org/guide/plugins，
and coding like this : 

    <div style="width:400px">
        <no-ssr>
               <ProductZoomer
                :base-images="images"
                :base-zoomer-options="zoomerOptions"
              ></ProductZoomer>
        </no-ssr>
    </div>

**Comment by MicroDreamIT** [comment]
@akulubala in nuxt I have used everything with no-ssr but thumblist is not showing when page switch, but if page refresh it works.
