### ISSUE TITLE
Unable to load Product Zoomer in data object

### ISSUE THREAD

**Issue by erpriyanka** [akulubala/vue-product-zoomer#40]
If I put the sample data in return object it displays the output but if I dynamically call the image object unable to load data in product zoomer data object

If I place this code it displays the output
images: {
        thumbs: [
          {
            id: 1,
            url:
              "http://localhost:8000/images/product/thumbs/MICMIMC30651-6.jpg"
          },
          {
            id: 2,
            url:
              "http://localhost:8000/images/product/thumbs/MICMIMC30651-61.jpg"
          }
        
        ],
        normal_size: [
          {
            id: 1,
            url:
              "http://localhost:8000/images/product/preview/MICMIMC30651-6.jpg"
          },
          {
            id: 2,
            url:
              "http://localhost:8000/images/product/preview/MICMIMC30651-61.jpg"
          }
        
        ],
        large_size: [
          {
            id: 1,
            url:
              "http://localhost:8000/images/product/original/MICMIMC30651-6.jpg"
          },
          {
            id: 2,
            url:
              "http://localhost:8000/images/product/original/MICMIMC30651-61.jpg"
          }
                  ]
      },
 But when I call dynamically 

data(){
            return {
                images:[],
                zoomerOptions: {
                    zoomFactor: 3,
                    pane: "pane",
                    hoverDelay: 300,
                    namespace: "zoomer-bottom",
                    move_by_click: false,
                    scroll_items: 4,
                    choosed_thumb_border_color: "#dd2c00",
                    scroller_position: "bottom",
                    zoomer_pane_position: "right"
                }
            }
        },

![1](https://user-images.githubusercontent.com/19527080/62123252-2b95c000-b2e5-11e9-8de5-8e4ed42b964f.jpg)
![2](https://user-images.githubusercontent.com/19527080/62123257-2e90b080-b2e5-11e9-82e1-06f0c479e678.jpg)

error: 1. Invalid prop: type check failed for prop "baseImages". Expected Object, got Array 
2. Product Zoomer Need Normal Size Image At Least!!!

**Comment by akulubala** [comment]
@erpriyanka image thumbs must provide for this plugin

**Comment by erpriyanka** [comment]
I called image:[]  in return function and I get the output which you can see on the first screenshot but unable to render images.

**Comment by akulubala** [comment]
@erpriyanka can you put all your reletive code here?

**Comment by akulubala** [comment]
Hi @erpriyanka I got your email, I think your problem is caused by Object change limitation from javascript, check the document here: https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats
