### ISSUE TITLE
z-index property

### ISSUE THREAD

**Issue by Enjoyer1** [akulubala/vue-product-zoomer#44]
Hello, I having the issue when I use the component in a div with z-index > 0, it is showing the zoom but its behind my container because it has a different z index.
I'm using v2.0.11

<img width="420" alt="Captura de Pantalla 2019-09-09 a la(s) 10 23 05" src="https://user-images.githubusercontent.com/34873511/64534586-13558f80-d2ec-11e9-996e-7a790fa80d2b.png">

**Comment by akulubala** [comment]
Hi @Enjoyer1 the div you use for contain this component should be with a position relative. Also, suggest you use a recent version

**Comment by Enjoyer1** [comment]
I added z-index to the class drift-zoom-pane and now is working fine.
