### ISSUE TITLE
abnormal behavior with navigation

### ISSUE THREAD

**Issue by maverickpravin** [akulubala/vue-product-zoomer#45]
I have been working with product zoomer quite a while its great.
Lately after updating i have found a navigation not working when scroller have single image.
![Capture12](https://user-images.githubusercontent.com/11708491/65668185-dfee6100-e05e-11e9-9e14-6e3a2cd0b67e.PNG)

**Comment by jraguilan** [comment]
> I have been working with product zoomer quite a while its great.
> Lately after updating i have found a navigation not working when scroller have single image.
> ![Capture12](https://user-images.githubusercontent.com/11708491/65668185-dfee6100-e05e-11e9-9e14-6e3a2cd0b67e.PNG)

Hi, try to set your 'scroll_items' to 1.
