### ISSUE TITLE
Cannot import locally

### ISSUE THREAD

**Issue by tduccuong** [akulubala/vue-product-zoomer#49]
Hi, 

thanks for nice work! 

But I cannot import the component locally. Always get 'template or rendered function not defined' error... I hade to import it in my main app.js and `Vue.use(ProductZoomer)` for it to work.

Could u pls help me on that? Thanks!

**Comment by akulubala** [comment]
@tduccuong ,you don't need import this from app.js, from your template, just write this three-line, it's the same:
```
import Vue from 'vue';
import ProductZoomer from 'vue-product-zoomer'
Vue.use(ProductZoomer)
```
