### ISSUE TITLE
programmatic method to chooseThumb

### ISSUE THREAD

**Issue by luhegi** [akulubala/vue-product-zoomer#5]
Hello, can you provide programmatic method to chooseThumb in example
when parent data changed, the product zoomer also navigate to selected thumb.
sorry if i asking too much

**Comment by akulubala** [comment]
@luhegi , For now these have no way to directly set choosedThumb.I can give you an idea to do this. when your parent data changed, you could reorder `images` data which will pass to product zoomer component.means reorder `images.thumbs`, 'images.normal_size', `images_large_size`
