### ISSUE TITLE
Vue Product Zoomer not working dynamically.

### ISSUE THREAD

**Issue by Suneel2019** [akulubala/vue-product-zoomer#50]
I am trying to dynamically use the vue product zoomer. I created a hook created that calls an api and gives the images data. The main concern is the vue-product-zoomer component renders before and searches for the normal_size image and throws error. 

Error in created hook: "Product Zoomer Need Normal Size Image At Least!!!"

Any Solution !!!!

**Comment by PH7-Jack** [comment]
Use v-if in condition loading
