### ISSUE TITLE
Routing breaks the image zoomer

### ISSUE THREAD

**Issue by julen-folky** [akulubala/vue-product-zoomer#51]
[UPDATE] I discovered that going from one page to another breaks the zoomer. I just placed a link from a page with zoomer in nuxt demo to another new page just containing a link back to the previous and reproduces the same error I discribe below.

I added [nuxt-i18n](https://github.com/nuxt-community/nuxt-i18n) to the demo project with nuxt at https://github.com/akulubala/nuxt-product-zoomer-demo. Then configured nuxt-i18n with the data in the [Basic Usage](https://github.com/nuxt-community/nuxt-i18n) section; adding to the page with the zoomer two links to change language.

First load is fine, but when clicking on the the link to change the language the thumbnails are no loger visible and while the main picture is present the zoom effect is gone.

When the change of the language happens some styles on the zoomer are change, visibility set to hidden etc; but I cannot understand why.

Any solution? Thank you very much!

**Comment by akulubala** [comment]
@julen-folky can you provide you demo project let us run locally? it's hard to locate the problem with that information you provided

**Comment by julen-folky** [comment]
Hi @akulubala! Yes, I [forked the repository](https://github.com/julen-folky/nuxt-product-zoomer-demo) and commited a change to reproduce issue according to the most recent descritption. Thanks for your time!

**Comment by akulubala** [comment]
Hi @julen-folky, I checked your demo, the component did not remount is because vue will reuse component as possible as it can. You need to make the page reload with goback link. I don't use much of NUXT. for vue there have a key can assign to `router-view` can force component reload

**Comment by julen-folky** [comment]
@akulubala I tried to force the reload of the component by adding `key` prop to it. Also by doing the same in a component that wraps zoomer (see the other branch); without luck in both cases 😞.

Could you add further insight? Thanks!

**Comment by VIkasaviox** [comment]
Hello @akulubala ,

Is this issue is fixed.
As i implemented this in vue and facing the same issue.
routing is breaking zoomer and also slider is not visible after visiting from a route.
When we refresh the page , it works fine.
Please let me know how it can be fixed

Thanks.

**Comment by akulubala** [comment]
this should be fixed with the new version

**Comment by aditya1996gupta** [comment]
I am facing  the same issue when visiting to other page the zoomer image breaks and i have to reload and refresh everytime any solution
please?
