### ISSUE TITLE
Nuxt.js with Bootstrap Vue Ui

### ISSUE THREAD

**Issue by jakupi1** [akulubala/vue-product-zoomer#54]
Hello 👋, im using productzoomer with b-modal and it doesn't works below is the code is use 
 
`  <b-modal 
ref="my-modal"
 centered
 modal-class="wcModal" 
hide-footer
 hide-header >
            <ProductZoomer :base-images="images" :base-zoomer-options="zoomerOptions"></ProductZoomer>
</b-modal>`

and look how it looks inside of the modal <img width="766" alt="Screenshot 2020-03-31 at 18 14 57" src="https://user-images.githubusercontent.com/32740979/78049622-91a67b80-737b-11ea-9bad-761077e1d478.png">

**Comment by smaharj1** [comment]
Looks like the issue here is that the modal is not rendered when the page loads. I see that using `nextTick` would solve this issue. 

@akulubala , can I grab this issue and work on it?

**Comment by akulubala** [comment]
Hi, @smaharj1 ， thanks helping, I'll merge and publish your pull request later.

**Comment by smaharj1** [comment]
> Hi, @smaharj1 ， thanks helping, I'll merge and publish your pull request later.

I think this would also solve #51

**Comment by jakupi1** [comment]
@smaharj1  Does your fix works? Because i forked and changed window load thing added nextTick still same issue :/

**Comment by smaharj1** [comment]
> @smaharj1 Does your fix works? Because i forked and changed window load thing added nextTick still same issue :/

I didn't try it in Nuxt but I just did it regularly in a web app with vue bootstrap. changing it to nextTick worked for me. Also, do you have the ProductZoomer somewhere else in that same page? If that's the case, it won't work but that's a separate issue.

**Comment by jakupi1** [comment]
@smaharj1 I added setTimeout (500) and it works.
