### ISSUE TITLE
add vue-product-zoomer in Nuxt js

### ISSUE THREAD

**Issue by AlexanderQuinaluiza** [akulubala/vue-product-zoomer#56]
problems integrating the component with nuxt:
`import ProductZoomer from 'vue-product-zoomer'
import readme from '../components/Reame'
export default {
  components: { readme, ProductZoomer },`
Error:
![imagen](https://user-images.githubusercontent.com/7355793/80291719-a1fd0c80-8715-11ea-952f-7191d294e87c.png)
I need your help please

**Comment by akulubala** [comment]
please check this demo. https://github.com/akulubala/nuxt-product-zoomer-demo
