### ISSUE TITLE
Attempting to Use Carousel

### ISSUE THREAD

**Issue by ovidales** [akulubala/vue-product-zoomer#6]
I am implementing a carousel using Vuetify but I am having a problem the zoom box is only shown in the first image, I made a change so that the image would be displayed from an array, you have some idea of why only the zoom box is shown in the first picture?

Thank you

**Comment by akulubala** [comment]
Hi @ovidales, not sure if your problem been solved or not.and if you could provide some code for your problem?

**Comment by ovidales** [comment]
Thanks for your response, I told you that I have already made it work.

**Comment by akulubala** [comment]
ok, np. then this issue is closed.
