### ISSUE TITLE
Image resizing and CSS

### ISSUE THREAD

**Issue by eduardobalbo** [akulubala/vue-product-zoomer#67]
I have a problem where i need the size of the component to be fixed to _500x500px_, because the area of my project where the zoomer will stay has that amount of space. 
My images are all _720x720px_, and i have more than _30.000_ of them, so resizing them manually is impossible. When i use one of them, the component size goes to the size of the image, and it breaks itself really weirdly, a white blank space stays between the thumblist and the actual image. 
I can't put any CSS classes on the component either, is there a way of fixing the image or the component size? On your example all the images had the same dimension? I think all i need to do is achievable by fixing the component size but i cant actually make CSS classes work with it. Also i'm using Nuxt.

**weird white space as mentioned when the selected image is smaller than the bigger one (wich also makes the component be the size of the bigger image)** 
![ss1](https://user-images.githubusercontent.com/67204830/93589520-4ad92c00-f983-11ea-8454-d0e35002e554.png)

**normal if the selected image is the bigger one (also the component size is the same)**
![ss2](https://user-images.githubusercontent.com/67204830/93589561-59bfde80-f983-11ea-8b0b-542b235c1f47.png)

### **_Template reference_**

```
<div class="zoomerExpress">
            <no-ssr>
                <product-zoomer
                    :base-images="images"
                    :base-zoomer-options="zoomerOptions"
                >
                </product-zoomer>
            </no-ssr>
        </div>

```

### **_data call_**

```
 data: function() {
            return {
                'images': {
                    'thumbs': [
                        {
                        'id': 1,
                        'url': 'https://via.placeholder.com/700'
                        },
                        {
                        'id': 2,
                        'url': 'https://via.placeholder.com/600'
                        },
                    ],
                    'normal_size': [
                        {
                        'id': 1,
                        'url': 'https://via.placeholder.com/700'
                        },
                        {
                        'id': 2,
                        'url': 'https://via.placeholder.com/600'
                        },
                    ],
                },

                'zoomerOptions': {
                    zoomFactor: 2,
                    pane: "container",
                    hoverDelay: 150,
                    namespace: "inline-container",
                    move_by_click: false,
                    scroll_items: 4,
                    choosed_thumb_border_color: "#d4d4d4",
                    scroller_position: "left"
                }
            }
        },
```

### **_CSS class_**
```

    .zoomerExpress {
        margin-left: 10px;
        max-width: 600px;
    }

```

**Comment by akulubala** [comment]
1. all the images had the same dimension
2. The image width on the left and right sides is proportional

**Comment by eduardobalbo** [comment]
Oh i see, any idea how i should deal with my case? I need the images to have a fixed size, and the component too. And also CSS dont seem to work on the component somehow, and sometimes i also have a bug that the component dosnt load until i refresh the page. Using this with nuxt gives a lot of issue it seems.

**Comment by akulubala** [comment]
you should put this component in a fixed-width container I believe, then control the container width to make the proportional properly

**Comment by eduardobalbo** [comment]
I see, i tried but it didnt work, it dosnt respect any CSS given, also there is a bug with nuxt routing that makes the component only appear after a page reload.
For now i'll try using another similar component, maybe i'll come back and try this one later, to many issue to fix atm. 
Thank you for the help.
