### ISSUE TITLE
Adjust the width and height

### ISSUE THREAD

**Issue by bobbygerez** [akulubala/vue-product-zoomer#7]
Hi there,
Is there a way to change the height and width of the preview? It's really different from your example.... Thanks. 
![untitled](https://user-images.githubusercontent.com/10149942/43000480-4c992a2c-8c2a-11e8-9b4d-5d227ec6ffad.png)
![2](https://user-images.githubusercontent.com/10149942/43000895-e6bee10e-8c2b-11e8-80b1-f7fb47f5fb51.PNG)

**Comment by akulubala** [comment]
Hi @bobbygerez, which browser you are using? I tested it on Chrome, Safari and Firefox. And please make sure all assets are loaded.

**Comment by maverickpravin** [comment]
Same issue ........ i have all the assets loaded and its working great.
But if i use with bootstrap grid, the same distortion starts to happen.
```
<div class="row">
	<div class="col-md-6">
		<product-detail />				
	</div>
</div>
```

**Comment by maverickpravin** [comment]
Same issue here. All my assets are loaded successfully.
It happens with bootstrap grid
```
<div class="row">
  <div class="col-md-6">
      <div style="width:400px">
        <no-ssr>
            <ProductZoomer
                :base-images="images"
                :base-zoomer-options="zoomerOptions"
            ></ProductZoomer>
        </no-ssr>
    </div>
  </div>
</div>
```
