### ISSUE TITLE
How to remove the thumb list?

### ISSUE THREAD

**Issue by mafrego** [akulubala/vue-product-zoomer#71]
Hi there!
Is there a way/option to remove/hide the thumb list(i.e. scroll items and scroll buttons ) and display only the image that you want to zoom?
Thank you!

**Comment by akulubala** [comment]
if you only want hover on one image, try this package https://github.com/imgix/drift @mafrego

**Comment by mafrego** [comment]
Thank you Raymond,
your vue-product-zoomer is perfect in order to be integrated with my vue
app, I just want to know if it would be possible to hide the scrollbar
somehow.
Thank you again!

Il giorno lun 30 nov 2020 alle ore 14:19 Raymond Cheng <
notifications@github.com> ha scritto:

**Comment by akulubala** [comment]
@mafrego for the moment, you can try to overwrite the thumb list div CSS 'thumb-list' make it display none, will add this feature when the upgrade to vue 3.

**Comment by mafrego** [comment]
I did it already but it doesn't work, both in my component and in the
ProductZoomer.vue of your module.
I ran the code again, refreshed the page, loaded a new page but the
scrollbar is still there.
I don't know why, any idea?

Il giorno lun 30 nov 2020 alle ore 14:37 Raymond Cheng <
notifications@github.com> ha scritto:

**Comment by mafrego** [comment]
It works only if I add !important:

`    .thumb-list {
        display: none !important;
    }`
